# Generated by Django 5.0.6 on 2024-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('bxp', models.PositiveSmallIntegerField()),
                ('uxb', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
