# Generated by Django 5.0.6 on 2024-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_item_delete_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('1', 'Abarrotes'), ('2', 'Mascota'), ('3', 'Linea Blanca')], max_length=50),
        ),
    ]
