# Generated by Django 5.0.6 on 2024-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_alter_item_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('Abarrotes', 'Abarrotes'), ('Mascota2', 'Mascota'), ('Linea Blanca', 'Linea Blanca')], max_length=50),
        ),
    ]
