# Generated by Django 5.0.6 on 2024-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_alter_item_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('aaa', 'Opción 1'), ('aaa', 'Opción 2'), ('aaa', 'Opción 3')], max_length=50),
        ),
    ]
