# Generated by Django 5.0.6 on 2024-07-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_proveedores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedor',
        ),
    ]
