# Generated by Django 5.0.6 on 2024-07-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_rename_proveedores_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='departamento',
            new_name='razonsocial',
        ),
    ]
