# Generated by Django 5.0.6 on 2024-07-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_rename_departamento_proveedor_razonsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='razonsocial',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
