# Generated by Django 5.0.6 on 2024-07-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0012_alter_proveedor_razonsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='razonsocial',
            field=models.PositiveSmallIntegerField(max_length=11),
        ),
    ]
