# Generated by Django 5.0.6 on 2024-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='razonsocial',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
