# Generated by Django 5.0.6 on 2024-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0015_alter_proveedor_razonsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
