# Generated by Django 5.0.6 on 2024-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0016_alter_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.CharField(default='En programación', max_length=20),
            preserve_default=False,
        ),
    ]
