# Generated by Django 5.0.6 on 2024-07-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0017_item_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estado',
        ),
    ]
