# Generated by Django 5.0.6 on 2024-07-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0019_pedido_pedidoitem_pedido_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
