# Generated by Django 5.0.6 on 2024-07-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0020_item_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
