# Generated by Django 5.0.6 on 2024-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0022_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bxp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='uxb',
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='modelo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='numerodeserie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
