# Generated by Django 5.2 on 2025-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0023_remove_item_bxp_remove_item_uxb_item_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.AddField(
            model_name='item',
            name='cpu_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='ProcessorType'),
        ),
        migrations.AddField(
            model_name='item',
            name='dept_per',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento [PER]'),
        ),
        migrations.AddField(
            model_name='item',
            name='disk_gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='DiskCapacityGB'),
        ),
        migrations.AddField(
            model_name='item',
            name='empleado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='IPAddress1'),
        ),
        migrations.AddField(
            model_name='item',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='motivo_estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='oficina',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='os_arch',
            field=models.CharField(blank=True, max_length=50, verbose_name='OSArchitecture'),
        ),
        migrations.AddField(
            model_name='item',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='OSName'),
        ),
        migrations.AddField(
            model_name='item',
            name='os_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='OSType'),
        ),
        migrations.AddField(
            model_name='item',
            name='piso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del proveedor'),
        ),
        migrations.AddField(
            model_name='item',
            name='ram_gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='TotalPhysicalMemory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fabricante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo/versión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numerodeserie',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
