# Generated by Django 5.2 on 2025-05-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0024_remove_item_cantidad_remove_item_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cpu_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
