# Generated by Django 5.2 on 2025-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0026_alter_item_dept_per_alter_item_disk_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
