# Generated by Django 5.2 on 2025-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0027_item_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(choices=[('Disco', 'Disco'), ('Memoria', 'Memoria'), ('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Kit inalámbrico', 'Kit inalámbrico')], max_length=50)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.CharField(choices=[('-', '-'), ('240 GB', '240 GB'), ('480 GB', '480 GB')], default='-', max_length=10)),
                ('memoria', models.CharField(blank=True, choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, choices=[('-', '-'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop')], max_length=10, null=True)),
            ],
        ),
    ]
