# Generated by Django 5.2 on 2025-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0028_equipamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='memoria',
            field=models.CharField(blank=True, choices=[('-', '-'), ('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], max_length=10, null=True),
        ),
    ]
