# Generated by Django 5.2 on 2025-05-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0029_alter_equipamiento_memoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
