# Generated by Django 5.2 on 2025-05-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0030_equipamiento_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='item',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
