# Generated by Django 5.2 on 2025-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0031_delete_categoria_remove_pedido_item_delete_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fecha_entregada_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
