# Generated by Django 5.2 on 2025-05-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0032_item_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cambio_reservado_a_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
