# Generated by Django 5.2 on 2025-07-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0035_pedidoitem_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='localidad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
