# Generated by Django 5.2 on 2025-07-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0036_remove_pedidoitem_localidad_pedido_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
