# Generated by Django 5.2 on 2025-07-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0037_pedidoitem_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
