# Generated by Django 5.2 on 2025-07-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0038_pedidoitem_estado_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='fecha_entregada_real',
        ),
    ]
