# Generated by Django 5.2 on 2025-07-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0039_remove_pedidoitem_fecha_entregada_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='zona',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
