# Generated by Django 5.2 on 2025-07-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0040_pedido_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='fecha_entregada_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
