# Generated by Django 5.2 on 2025-07-02 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0041_pedidoitem_fecha_entregada_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('venta_proyectada', models.IntegerField()),
                ('venta_real', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.item')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMAPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('mape', models.FloatField()),
                ('cantidad_registros', models.IntegerField()),
                ('tipo_error', models.CharField(choices=[('Favorable', 'Favorable'), ('Desfavorable', 'Desfavorable'), ('Mixto', 'Mixto')], default='Mixto', max_length=20)),
                ('proyecciones_incluidas', models.ManyToManyField(blank=True, to='Academico.proyeccionventa')),
            ],
        ),
    ]
