# Generated by Django 5.2 on 2025-07-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0043_remove_equipamiento_numero_serie_equipamiento_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='codigo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
