# Generated by Django 5.2 on 2025-07-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0044_alter_equipamiento_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='estado',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='numero_serie',
            field=models.CharField(default='SIN SERIE', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
