# Generated by Django 5.2 on 2025-07-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0045_remove_equipamiento_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='codigo',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='estado',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Aplicado', 'Aplicado')], default='Reservado', max_length=10),
        ),
    ]
