# Generated by Django 5.2 on 2025-07-03 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0046_remove_equipamiento_numero_serie_equipamiento_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEquipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Aplicado', 'Aplicado')], default='Reservado', max_length=10)),
                ('fecha_entrega_estimada', models.DateField()),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academico.equipamiento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='Academico.pedido')),
            ],
        ),
    ]
